# Generated by Django 5.0.6 on 2024-06-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabado',
            fields=[
                ('id_acabado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'acabado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadDiaria',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actividad', models.DateField()),
            ],
            options={
                'db_table': 'actividad_diaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AqlCodigo',
            fields=[
                ('id_aql_codigo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('tamaño_muestra', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'aql_codigo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AqlLoteRango',
            fields=[
                ('id_aql_lote_rango', models.AutoField(primary_key=True, serialize=False)),
                ('min_lote', models.IntegerField()),
                ('max_lote', models.IntegerField()),
            ],
            options={
                'db_table': 'aql_lote_rango',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AqlMuestra',
            fields=[
                ('id_aql_muestra', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aql_muestra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AqlNivel',
            fields=[
                ('id_aql_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'aql_nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AqlResultadoRango',
            fields=[
                ('max_aceptacion', models.IntegerField()),
                ('min_rechazo', models.IntegerField()),
                ('id_aql_resultado_rango', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aql_resultado_rango',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AqlSignificancia',
            fields=[
                ('id_aql_significancia', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_significancia', models.DecimalField(decimal_places=3, max_digits=4, unique=True)),
            ],
            options={
                'db_table': 'aql_significancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CajaLote',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'caja_lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CajaPrenda',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'caja_prenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CajaSalida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField()),
            ],
            options={
                'db_table': 'caja_salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Confeccion',
            fields=[
                ('id_confeccion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'confeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id_correo', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id_corte', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'corte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionConfeccion',
            fields=[
                ('id_dim_confeccion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dimension_confeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionCorte',
            fields=[
                ('id_dim_corte', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dimension_corte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionMateriaPrima',
            fields=[
                ('id_dim_materia_prima', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dimension_materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionPartePrenda',
            fields=[
                ('id_dim_parte_prenda', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dimension_parte_prenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionPrenda',
            fields=[
                ('id_dim_prenda', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dimension_prenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.DecimalField(decimal_places=0, max_digits=8, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=15)),
                ('primer_apellido', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=3)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=3)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'espacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id_estanteria', models.DecimalField(decimal_places=0, max_digits=7, primary_key=True, serialize=False)),
                ('ancho_estanteria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('largo_estanteria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('alto_estanteria', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'estanteria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstiloPrenda',
            fields=[
                ('id_estilo_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'estilo_prenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaConfeccion',
            fields=[
                ('id_guia_confeccion', models.AutoField(primary_key=True, serialize=False)),
                ('medida_pecho', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medida_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medida_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medida_hombro', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medida_longitud', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medida_manga', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medida_muslo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'guia_confeccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspeccionCalidad',
            fields=[
                ('id_inspeccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inspeccion', models.DateTimeField()),
                ('cantidad_defectuosos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspeccion_calidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspeccionDescripcion',
            fields=[
                ('id_descripcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'inspeccion_descripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteEntrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateTimeField()),
            ],
            options={
                'db_table': 'lote_entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteSalida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField()),
            ],
            options={
                'db_table': 'lote_salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad_total', models.IntegerField()),
            ],
            options={
                'db_table': 'maquina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id_materia_prima', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id_orden_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProducción',
            fields=[
                ('id_orden_producción', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'orden_producción',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id_orden_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('prioridad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'orden_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id_pasillo', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('largo_pasillo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ancho_pasillo', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'pasillo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'plan_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_prenda', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('denominacion_social', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'db_table': 'talla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'telefono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCorte',
            fields=[
                ('id_tipo_corte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_corte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLote',
            fields=[
                ('id_tipo_lote', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'tipo_lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMateriaPrima',
            fields=[
                ('id_tipo_materia_prima', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'tipo_materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPartePrenda',
            fields=[
                ('id_tipo_parte_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tipo_parte_prenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id_tipo_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'tipo_prenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=19, unique=True)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadoActividad',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.actividaddiaria')),
                ('cantidad_hecha', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaquinaActividad',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.actividaddiaria')),
                ('cantidad_hecha', models.IntegerField()),
            ],
            options={
                'db_table': 'maquina_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroTransformacionCaja',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.actividaddiaria')),
            ],
            options={
                'db_table': 'registro_transformacion_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroUsoLote',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.actividaddiaria')),
                ('cantidad_usada', models.IntegerField()),
            ],
            options={
                'db_table': 'registro_uso_lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimConfeccionDetalle',
            fields=[
                ('id_dim_confeccion', models.OneToOneField(db_column='id_dim_confeccion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.dimensionconfeccion')),
            ],
            options={
                'db_table': 'dim_confeccion_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParteCorteDetalle',
            fields=[
                ('id_dim_parte_prenda', models.OneToOneField(db_column='id_dim_parte_prenda', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.dimensionparteprenda')),
                ('medida', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'parte_corte_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPrendaDetalle',
            fields=[
                ('id_dim_prenda', models.OneToOneField(db_column='id_dim_prenda', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.dimensionprenda')),
            ],
            options={
                'db_table': 'dim_prenda_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroLoteCaja',
            fields=[
                ('id_lote', models.OneToOneField(db_column='id_lote', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.lote')),
                ('fecha_transicion', models.DateField()),
            ],
            options={
                'db_table': 'registro_lote_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id_orden_pedido', models.OneToOneField(db_column='id_orden_pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.ordenpedido')),
            ],
            options={
                'db_table': 'pedido_detalle',
                'managed': False,
            },
        ),
    ]
