name: Update Contributors

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta el script cada hora
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Date and Time
        id: check_time
        run: |
          end_date="2024-06-29T19:00:00Z"
          current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Current date: $current_date"
          if [[ "$current_date" > "$end_date" ]]; then
            echo "Date has passed end date"
            exit 0
          fi

      - name: Set up Git
        if: steps.check_time.outcome == 'success'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Generate contributors list
        if: steps.check_time.outcome == 'success'
        run: |
          git shortlog -s -n -e > contributors.txt

      - name: Update README.md
        if: steps.check_time.outcome == 'success'
        run: |
          {
            echo "| Autor | Número de Commits |"
            echo "| --- | --- |"
            while read -r line; do
              commits=$(echo $line | awk '{print $1}')
              author=$(echo $line | awk '{$1=""; print $0}')
              echo "| $author | $commits |"
            done < contributors.txt
          } > new_contributors.md

          # Insertar la nueva sección de contribuyentes en el marcador
          awk '1;/<!--CONTRIBUTORS-->/ { system("cat new_contributors.md") }' README.md > new_README.md
          mv new_README.md README.md

      - name: Commit and push changes
        if: steps.check_time.outcome == 'success'
        run: |
          git add README.md
          git commit -m "Actualizar README con la lista de contribuyentes"
          git push
